// Code generated by generate_reads.go; DO NOT EDIT.
package packets

import "bytes"

func (p *ClientInfoPacket) Read(r *bytes.Reader) error {
	if err := p.Locale.Read(r); err != nil { return err }
	if err := p.ViewDistance.Read(r); err != nil { return err }
	if err := p.ChatMode.Read(r); err != nil { return err }
	if err := p.ChatColors.Read(r); err != nil { return err }
	if err := p.DisplayedSkinParts.Read(r); err != nil { return err }
	if err := p.MainHand.Read(r); err != nil { return err }
	if err := p.EnableTextFiltering.Read(r); err != nil { return err }
	if err := p.AllowServerListings.Read(r); err != nil { return err }
	return nil
}

func (p *AckFinishConfigPacket) Read(r *bytes.Reader) error {
	return nil
}

func (p *ConfigKeepAlivePacket) Read(r *bytes.Reader) error {
	if err := p.KeepAliveID.Read(r); err != nil { return err }
	return nil
}

func (p *LoginStartPacket) Read(r *bytes.Reader) error {
	if err := p.Name.Read(r); err != nil { return err }
	if err := p.PlayerUUID.Read(r); err != nil { return err }
	return nil
}

func (p *EncryptionRespPacket) Read(r *bytes.Reader) error {
	if err := p.SharedSecret.Read(r); err != nil { return err }
	if err := p.VerifyToken.Read(r); err != nil { return err }
	return nil
}

func (p *LoginAckPacket) Read(r *bytes.Reader) error {
	return nil
}

func (p *HandshakePacket) Read(r *bytes.Reader) error {
	if err := p.ProtocolVersion.Read(r); err != nil { return err }
	if err := p.ServerAddr.Read(r); err != nil { return err }
	if err := p.ServerPort.Read(r); err != nil { return err }
	if err := p.RequestType.Read(r); err != nil { return err }
	return nil
}

func (p *StatusReqPacket) Read(r *bytes.Reader) error {
	return nil
}

func (p *PingReqPacket) Read(r *bytes.Reader) error {
	if err := p.Timestamp.Read(r); err != nil { return err }
	return nil
}

func (p *StatusRespPacket) Read(r *bytes.Reader) error {
	if err := p.Response.Read(r); err != nil { return err }
	return nil
}

